---
- name: Validar despliegue WebLogic y estado de la app
  hosts: all
  become: false

  tasks:

    - name: Definir app y versión
      set_fact:
        app_name: "{{ app_name }}"
        app_version: "{{ app_version }}"

    - name: Cargar variables de configuración
      include_vars:
        file: "../vars/{{ app_name }}.yml"
        name: app_vars

    - name: Fecha de verificación
      set_fact:
        fecha_verificacion: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

    - name: Verificar app levantada
      uri:
        url: "http://{{ app_vars.dominio }}:7001/{{ app_name }}/"
        method: GET
        return_content: yes
        status_code: 200
        timeout: 10
      register: app_check
      retries: 5
      delay: 15
      until: app_check.status == 200

    - name: Medir tiempo de respuesta
      set_fact:
        tiempo_respuesta_ms: "{{ (app_check.elapsed * 1000) | round(0) }}"

    - name: Validar velocidad de respuesta
      assert:
        that:
          - tiempo_respuesta_ms < 5000
        fail_msg: "⚠️ Tiempo alto: {{ tiempo_respuesta_ms }}ms"
        success_msg: "✅ Tiempo: {{ tiempo_respuesta_ms }}ms"

    - name: Guardar log post-deploy
      copy:
        content: |
          [{{ fecha_verificacion }}] Verificación WebLogic
          App: {{ app_name }} v{{ app_version }}
          URL: http://{{ app_vars.dominio }}:7001/{{ app_name }}/
          Código HTTP: {{ app_check.status }}
          Tiempo: {{ tiempo_respuesta_ms }} ms
          HTML: {{ app_check.content[:200] | default('Sin contenido') }}
        dest: "/opt/logs/verify_{{ app_name }}_{{ fecha_verificacion }}.log"
        mode: '0644'

    - name: Traer log al workspace Jenkins
      fetch:
        src: "/opt/logs/verify_{{ app_name }}_{{ fecha_verificacion }}.log"
        dest: "logs/"
        flat: yes
