---
- name: Validar despliegue de aplicación
  hosts: weblogic_servers
  vars_files:
    - "../vars/{{ app_name }}.yml"

  tasks:
    - name: Definir URL de prueba
      set_fact:
        test_url: "http://{{ ansible_host }}:7001{{ app_config.context_root }}/health"

    - name: Esperar disponibilidad de la aplicación
      uri:
        url: "{{ test_url }}"
        method: GET
        status_code: 200
        timeout: 30
        body_format: json
      register: health_check
      until: health_check.status == 200
      retries: 10
      delay: 10

    - name: Registrar resultados de validación
      template:
        src: templates/postdeploy_log.j2
        dest: "{{ paths.logs_dir }}/postdeploy_{{ app_config.name }}_{{ app_config.version }}.log"
        mode: '0644'

    - name: Recuperar log para Jenkins
      fetch:
        src: "{{ paths.logs_dir }}/postdeploy_{{ app_config.name }}_{{ app_config.version }}.log"
        dest: "logs/"
        flat: yes
