---
- name: Validar despliegue WebLogic y estado de la app
  hosts: all
  become: false

  tasks:

    - name: Definir app y versión
      set_fact:
        app_name: "{{ app_name }}"
        app_version: "{{ app_version }}"

    - name: Cargar variables de configuración
      include_vars:
        file: "../vars/{{ app_name }}.yml"
        name: app_vars

    - name: Fecha de verificación
      set_fact:
        fecha_verificacion: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

    - name: Verificar app levantada (no bloquea si falla)
      uri:
        url: "http://{{ app_vars.dominio }}:7001/{{ app_name }}/"
        method: GET
        return_content: yes
        status_code: 200
        timeout: 10
      register: app_check
      ignore_errors: true

    - name: Guardar log post-deploy
      copy:
        content: |
          [{{ fecha_verificacion }}] Verificación WebLogic
          App: {{ app_name }} v{{ app_version }}
          URL: http://{{ app_vars.dominio }}:7001/{{ app_name }}/
          Código HTTP: {{ app_check.status | default('No disponible') }}
          HTML: {{ app_check.content[:200] | default('Sin contenido') }}
        dest: "/opt/logs/verify_{{ app_name }}_{{ fecha_verificacion }}.log"
        mode: '0644'

    - name: Traer log al workspace Jenkins
      fetch:
        src: "/opt/logs/verify_{{ app_name }}_{{ fecha_verificacion }}.log"
        dest: "logs/"
        flat: yes
