---
- name: Preparar entorno WebLogic
  hosts: weblogic_servers
  vars_files:
    - "../vars/{{ app_name }}.yml"  # Carga las variables primero

  tasks:
    # Debug: Verificar variables cargadas
    - name: Mostrar variables cargadas
      debug:
        var: app_config
      when: app_config is defined

    # Definir variables en ORDEN CORRECTO
    - name: Definir war_file (PRIMERO)
      set_fact:
        war_file: "{{ app_config.name }}-{{ app_config.version }}.war"

    - name: Definir rutas derivadas (DESPUÉS)
      set_fact:
        war_path: "{{ paths.deploy_dir }}/{{ app_config.name }}/{{ war_file }}"
        full_nexus_url: "{{ nexus_config.url }}/{{ app_config.nexus_path }}/{{ app_config.name }}/{{ app_config.version }}/{{ war_file }}"

    # Verificar resultados
    - name: Mostrar variables generadas
      debug:
        msg:
          - "Archivo WAR: {{ war_file }}"
          - "Ruta destino: {{ war_path }}"
          - "URL Nexus: {{ full_nexus_url }}"
