---
- name: Preparar entorno WebLogic antes del despliegue
  hosts: all
  become: false

  tasks:

    - name: Definir nombre de aplicación
      set_fact:
        app_name: "{{ app_name }}"
        app_version: "{{ app_version }}"

    - name: Incluir variables específicas de la app
      include_vars:
        file: "../vars/{{ app_name }}.yml"
        name: app_vars

    - name: Generar nombre de archivo WAR
      set_fact:
        war_file: "{{ app_vars.app_name }}-{{ app_vars.app_version }}.war"

    - name: Generar ruta y URL del WAR
      set_fact:
        war_path: "/opt/deploy/{{ app_vars.app_name }}/{{ war_file }}"
        war_url: "http://192.168.1.131:8081/repository/maven-releases/com/empresa/web/{{ app_vars.app_name }}/{{ app_vars.app_version }}/{{ war_file }}"

    - name: Verificar puerto 7001 (AdminServer)
      wait_for:
        port: 7001
        state: started
        timeout: 30

    - name: Crear carpeta de despliegue si no existe
      file:
        path: "/opt/deploy/{{ app_vars.app_name }}"
        state: directory
        mode: '0755'

    - name: Eliminar WAR previo si existe
      file:
        path: "{{ war_path }}"
        state: absent

    - name: Descargar WAR desde Nexus
      get_url:
        url: "{{ war_url }}"
        dest: "{{ war_path }}"
        mode: '0644'
        url_username: "{{ app_vars.nexus_user }}"
        url_password: "{{ app_vars.nexus_pass }}"
        use_netrc: false

    - name: Obtener hash SHA256 del WAR
      command: "sha256sum {{ war_path }}"
      register: war_hash_result
      changed_when: false

    - name: Verificar hash del WAR con el esperado
      assert:
        that:
          - "war_hash_result.stdout.split()[0] == app_vars.expected_sha256"
        fail_msg: "❌ El WAR descargado no coincide con el hash esperado"
        success_msg: "✅ Integridad confirmada vía SHA256"

    - name: Crear carpeta de logs si no existe
      become: true
      file:
        path: "/opt/logs"
        state: directory
        mode: '0755'

    - name: Guardar log de preparación
      copy:
        content: |
          [{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}] Preparación de entorno WebLogic:
          App: {{ app_name }} v{{ app_version }}
          WAR: {{ war_path }}
          Hash actual: {{ war_hash_result.stdout.split()[0] }}
          Hash esperado: {{ app_vars.expected_sha256 }}
        dest: "/opt/logs/prepare_{{ app_name }}_{{ app_version }}.log"
        mode: '0644'

    - name: Traer log al workspace Jenkins
      fetch:
        src: "/opt/logs/prepare_{{ app_name }}_{{ app_version }}.log"
        dest: "logs/"
        flat: yes
