---
- name: Rollback de aplicación en WebLogic
  hosts: all
  become: false

  tasks:

    - name: Cargar variables de la aplicación
      include_vars:
        file: "../vars/{{ app_name }}.yml"
        name: app_vars

    - name: Definir nombre del archivo WAR y ruta
      set_fact:
        war_file: "{{ app_vars.app_name }}-{{ app_vars.app_version }}.war"
        war_path: "/opt/deploy/{{ app_vars.app_name }}/{{ war_file }}"

    - name: Definir fecha de rollback
      set_fact:
        fecha_rollback: "{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"

    - name: Crear carpeta de logs si no existe
      file:
        path: "/opt/logs"
        state: directory
        mode: '0755'

    - name: Ejecutar rollback (undeploy)
      shell: |
        java weblogic.Deployer \
          -adminurl t3://{{ app_vars.dominio }}:7001 \
          -username {{ wl_user }} \
          -password {{ wl_pass }} \
          -undeploy \
          -name {{ app_vars.app_name }} \
          -targets {{ app_vars.targets }} \
          -verbose
      register: rollback_result
      ignore_errors: true

    - name: Mostrar resultado del rollback
      debug:
        var: rollback_result.stdout_lines

    - name: Guardar log del rollback
      copy:
        content: |
          [{{ fecha_rollback }}] Rollback WebLogic:
          App: {{ app_vars.app_name }} v{{ app_vars.app_version }}
          Resultado:
          {{ rollback_result.stdout }}
        dest: "/opt/logs/rollback_{{ app_vars.app_name }}_{{ fecha_rollback }}.log"
        mode: '0644'

    - name: Traer log al workspace Jenkins
      fetch:
        src: "/opt/logs/rollback_{{ app_vars.app_name }}_{{ fecha_rollback }}.log"
        dest: "logs/"
        flat: yes

