---
- name: Rollback de aplicación en WebLogic
  hosts: weblogic_servers
  vars_files:
    - "../vars/{{ app_name }}.yml"

  tasks:
    - name: Detener aplicación
      command: >
        java weblogic.Deployer
        -adminurl {{ weblogic_config.admin_url }}
        -username {{ wl_user }}
        -password {{ wl_pass }}
        -stop
        -name {{ app_config.name }}
        -targets {{ weblogic_config.targets }}
      register: stop_result
      ignore_errors: true
      no_log: true

    - name: Eliminar aplicación
      command: >
        java weblogic.Deployer
        -adminurl {{ weblogic_config.admin_url }}
        -username {{ wl_user }}
        -password {{ wl_pass }}
        -undeploy
        -name {{ app_config.name }}
        -targets {{ weblogic_config.targets }}
      register: undeploy_result
      no_log: true

    - name: Registrar log de rollback
      template:
        src: templates/rollback_log.j2
        dest: "{{ paths.logs_dir }}/rollback_{{ app_config.name }}_{{ app_config.version }}.log"
        mode: '0644'

    - name: Recuperar log para Jenkins
      fetch:
        src: "{{ paths.logs_dir }}/rollback_{{ app_config.name }}_{{ app_config.version }}.log"
        dest: "logs/"
        flat: yes
